title: The Canadian Cropland dataset
description: A dataset descriptor website for the Canadian Cropland dataset
theme: just-the-docs

url: https://bioinfouqam.github.io/the-canadian-cropland-dataset-website/

aux_links:
  Paper: https://arxiv.org/abs/2306.00114

nav_external_links:
  - title: The Canadian Cropland Dataset on GitHub
    url: https://github.com/bioinfoUQAM/Canadian-cropland-dataset